title: Slurm
description: 这里是对博客的描述。
show_downloads: false

baseurl: "/slurm" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://moyu5021.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: XuJing
#image: /thumbnail-jumbo.png
image: images/yuzhou.jpeg

#twitter:
#  username: xujing

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['event', 'author', 'contact']

collections:
  authors:
    output: true
#    permalink: author/:title/

defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
