title: Slurm
description: Slurm(Simple Linux Utility for Resource Management， http://slurm.schedmd.com/ )是开源的、具有容错性和高度可扩展的Linux集群超级计算系统资源管理系统.
show_downloads: false

baseurl: "/slurm" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://moyu5021.github.io/slurm" # change this to the base hostname & protocol for your site

widgets:
- category
- tag
- links
- rss


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%Y %b %-d"

theme: # leave it empty
imglogo:
    enable: true
    src: images/slurm_logo.png

# social
author: XuJing
#image: /thumbnail-jumbo.png
image: images/yuzhou.jpeg

#twitter:
#  username: xujing

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['about','event', 'author','lecture','contact']

collections:
  authors:
    output: true
#    permalink: author/:title/

defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
