title: Slurm
description: Slurm(Simple Linux Utility for Resource Management， http://slurm.schedmd.com/ )是开源的、具有容错性和高度可扩展的Linux集群超级计算系统资源管理和作业调度系统。超级计算系统可利用Slurm对资源和作业进行管理，以避免相互干扰，提高运行效率。所有需运行的作业，无论是用于程序调试还是业务计算，都可以通过交互式并行 srun 、批处理式 sbatch 或分配式 salloc 等命令提交，提交后可以利用相关命令查询作业状态等。
show_downloads: false

baseurl: "/slurm" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://moyu5021.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty
imglogo:
    enable: true
    src: images/slurm_logo.png

# social
author: XuJing
#image: /thumbnail-jumbo.png
image: images/yuzhou.jpeg

#twitter:
#  username: xujing

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['about', 'event', 'author', 'contact']

collections:
  authors:
    output: true
#    permalink: author/:title/

defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
